import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import Header from '@/components/Header'
import Footer from '@/components/Footer'
import MenuItem from '@/components/MenuItem'
import SideNavigation from '@/components/SideNavigation'
import Card from '@/components/Card'


export default function Home() {
  return (
    <>
      <Head>
        <title>Assesment 1</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
      
        
        <div className={styles.container}>
        <SideNavigation/>
          <div className={styles.stuff}>
          <Header/>
          <div className={styles.cardContainer}>
            <div className={styles.first}>
              <Card title="Experience" description="Highschool Courses" borderColor="var(--purple)"/>
              <Card title="Projects" description="Coding a website using nextjs" borderColor="var(--pink)"/>
              <Card title="Skills" description="Computer science, Linux, Programming, Animation, Adobe" borderColor="var(--blue)"/>
            </div>
            <div className={styles.first}>
            <Card title="Education" description="BCIT Digital Design and Development" borderColor="var(--darkblue)"/>
            <Card title="Volunteering" description="Tree Island Steel Christmas Party helping at the registration desk" borderColor="var(--teal)"/>
            <Card title="Interests" description="I like music, badminton" borderColor="var(--lightgreen)"/>
            </div>
          </div>
          <Footer/>
          </div>
        </div>
      </main>
    </>
  )
}
